mysql:
  host: localhost
  port: 3306
  database: test
  username: username
  password: password
  tablename: tablename

#The placeholders to save in the database.
#For name: value, the name will be used in the sql table and the value will be the placeholder to replace.

placeholders:
  #mysql_column_name: 'placeholder'
  player_name: '%player_name%'
  player_uuid: '%player_uuid%'

